---
title: "Project Checklist"
subtitle: STAT 184 Course Project
author: Jaikhush Thakkar
date: 30 June 2025
date-format: 30/6/2025
toc: true
format: pdf
editor: source
---

# Purpose

This document is required to indicate where various requirements can be found within the `QMD` file that produced your Final Project Report (PDF). You must indicate line numbers as they appear in your final `QMD` document accompanying each of the following required tasks. Points will be deducted if line numbers are missing or differ significantly from the `QMD` of your submitted Report.

# Final Project Requirements

-   [x] Set a table of contents.
-   [x] Use a consistent Style Guide.
-   [x] Identify and use at least 3 data sets/sources.
-   [x] Include all required parts of the report (e.g., Introduction, etc.).
-   [x] Caption all figures and use **cross references** within your Quarto document.
-   [x] Put all code in the Code Appendix.
-   [x] Cite your sources. (Origin of your data, any websites you used, etc.)

# Line Numbers for Required Components

## Data Access

A. QMD line numbers where at least 3 data sources are imported:\
**Lines 60–84**

## Data Wrangling / Cleaning / etc.

**DO AT LEAST FOUR OF THE FOLLOWING:**

A. QMD line number(s) for general data wrangling:\
**Lines 95–101**, **Lines 122-130**, **Lines 147–154**

B. QMD line number(s) for a join operation:\
*(Not used)*

C. QMD line number(s) for `pivot_wider` or `pivot_longer` operation:\
**Line 124** , **Line 131**

D. QMD line number(s) for use of regular expressions:\
**Line 150**

E. QMD line number(s) for use of reduction and/or transformation functions:\
**Lines 95–101**, **Lines 122-130**, **Lines 147–154**

F. QMD line number(s) for use of user-defined functions:\
*(Not used)*

G. QMD line number(s) for use of loops and/or control flow:\
*(Not used)*

## Data Visualization

A. QMD line number(s) for **all data visualizations**:\
**Lines 109–116**, **Lines 134–140**, **Lines 156–163**

B. QMD line number(s) for multiple different geoms:\
**Line110** , **Line 157** , **Line 158**

C. QMD line number(s) for use of multiple aesthetics:\
**Line 109** , **Line 134** , **Line 136**

D. QMD line number(s) for use of layered graphics:\
**Lines 157-158**

E. QMD line number(s) for use of leaflet or choropleth maps:\
*(Not used)*

## Tables

A. Include QMD line numbers for **all tables**:\
**Lines 106**, **Lines132**
